# Generated by Django 5.2.4 on 2025-07-24 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteasset',
            name='key',
            field=models.CharField(blank=True, help_text="Khóa để phân biệt asset (ví dụ 'logo-header')", max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='siteasset',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
