# Generated by Django 5.2.4 on 2025-07-21 09:15

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_printmaterial_servicecategory_slug_printoption_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Đơn Hàng', 'verbose_name_plural': 'Các đơn hàng'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Sản phẩm', 'verbose_name_plural': 'Các sản phẩm'},
        ),
        migrations.AlterModelOptions(
            name='servicecategory',
            options={'verbose_name': 'Dịch vụ', 'verbose_name_plural': 'Các dịch vụ'},
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Hình Ảnh'),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Tên Dịch Vụ'),
        ),
    ]
