# Generated by Django 5.2.4 on 2025-07-24 16:07

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_siteasset_key_alter_siteasset_uploaded_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='price',
        ),
        migrations.RemoveField(
            model_name='service',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='siteasset',
            name='file',
        ),
        migrations.RemoveField(
            model_name='siteasset',
            name='name',
        ),
        migrations.RemoveField(
            model_name='siteasset',
            name='uploaded_at',
        ),
        migrations.AddField(
            model_name='siteasset',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='siteasset',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='core.category', verbose_name='Danh mục'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Mô tả'),
        ),
        migrations.AlterField(
            model_name='service',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Phổ biến'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Tên dịch vụ'),
        ),
        migrations.AlterField(
            model_name='service',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tiêu đề'),
        ),
        migrations.AlterField(
            model_name='serviceoption',
            name='laminate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.laminate', verbose_name='Cán màng'),
        ),
        migrations.AlterField(
            model_name='serviceoption',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.material', verbose_name='Chất liệu'),
        ),
        migrations.AlterField(
            model_name='serviceoption',
            name='paper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.paper', verbose_name='Giấy'),
        ),
        migrations.AlterField(
            model_name='serviceoption',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='core.service', verbose_name='Dịch vụ'),
        ),
        migrations.AlterField(
            model_name='serviceoption',
            name='shape',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.shape', verbose_name='Hình dạng'),
        ),
        migrations.AlterField(
            model_name='serviceoption',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.size', verbose_name='Kích thước'),
        ),
    ]
