# Generated by Django 5.2.4 on 2025-07-24 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_service_price_remove_service_unit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceoption',
            name='price',
        ),
        migrations.RemoveField(
            model_name='serviceoption',
            name='quantity',
        ),
        migrations.CreateModel(
            name='ServicePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Số lượng')),
                ('price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Giá (VND)')),
                ('laminate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.laminate', verbose_name='Cán màng')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.material', verbose_name='Chất liệu')),
                ('paper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.paper', verbose_name='Loại giấy')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.service', verbose_name='Dịch vụ')),
                ('shape', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.shape', verbose_name='Hình dạng')),
                ('size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.size', verbose_name='Kích thước')),
            ],
            options={
                'verbose_name': 'Bảng giá dịch vụ',
                'verbose_name_plural': 'Bảng giá dịch vụ',
                'unique_together': {('service', 'paper', 'size', 'laminate', 'material', 'quantity')},
            },
        ),
    ]
