# Generated by Django 5.2.4 on 2025-07-25 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_serviceoption_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address_detail',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='district',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping',
            field=models.CharField(choices=[('delivery', 'Giao tận nơi'), ('pickup', 'Đến lấy')], default='pickup', max_length=10),
        ),
    ]
