# Generated by Django 5.2.4 on 2025-07-22 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_siteasset_service_is_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Phổ biến'),
        ),
    ]
