# Generated by Django 5.2.4 on 2025-07-22 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_service_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecategory',
            name='show_on_homepage',
            field=models.BooleanField(default=False, verbose_name='Hiển thị ở trang chủ'),
        ),
    ]
