# Generated by Django 5.2.4 on 2025-07-22 09:23

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_servicecategory_show_on_homepage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteasset',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='siteasset',
            name='key',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
