# Generated by Django 5.2.4 on 2025-07-26 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_order_laminate_order_shape'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_code',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
def set_order_codes(apps, schema_editor):
    Order = apps.get_model('core', 'Order')
    from datetime import datetime

    prefix = datetime.now().strftime('%y%m%d')

    for i, order in enumerate(Order.objects.all(), start=1):
        order.order_code = f"{prefix}-OLD-{i}"
        order.save()