# Generated by Django 5.2.4 on 2025-07-26 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_order_order_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_code',
        ),
    ]
