# Generated by Django 5.2.4 on 2025-07-26 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_order_order_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_code',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
