# Generated by Django 5.2.4 on 2025-07-26 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_order_order_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Chưa thanh toán'), ('paid', 'Đã thanh toán'), ('processing', 'Đang tiến hành'), ('completed', 'Đã hoàn thành')], default='pending', max_length=20),
        ),
    ]
